/* =====================================================
   單字庫 — 每個主題至少 20 個單字
   欄位：en 英文、zh 中文、emoji 圖示、
        sen 英文例句、szh 中文例句、sfx 音效代號
   想新增單字：直接照格式加一行即可
   ===================================================== */
const THEMES = [
  {
    id: 'vehicles',
    name: '交通工具',
    emoji: '🚗',
    color: '#4ecdc4',
    words: [
      { en: 'car', zh: '車車', emoji: '🚗', sen: 'The car goes beep beep.', szh: '車車叭叭叫。', sfx: 'horn' },
      { en: 'bus', zh: '公車', emoji: '🚌', sen: 'The bus is big.', szh: '公車好大呀。', sfx: 'engine' },
      { en: 'train', zh: '火車', emoji: '🚂', sen: 'The train goes choo choo.', szh: '火車嘟嘟叫。', sfx: 'train' },
      { en: 'airplane', zh: '飛機', emoji: '✈️', sen: 'The airplane flies high.', szh: '飛機飛得好高。', sfx: 'plane' },
      { en: 'boat', zh: '小船', emoji: '⛵', sen: 'The boat is on the water.', szh: '小船在水上漂。', sfx: 'boat' },
      { en: 'bicycle', zh: '腳踏車', emoji: '🚲', sen: 'I ride my bicycle.', szh: '我騎腳踏車。', sfx: 'bell' },
      { en: 'motorcycle', zh: '摩托車', emoji: '🏍️', sen: 'The motorcycle is fast.', szh: '摩托車跑得快。', sfx: 'engine' },
      { en: 'truck', zh: '卡車', emoji: '🚚', sen: 'The truck carries toys.', szh: '卡車載著玩具。', sfx: 'engine' },
      { en: 'taxi', zh: '計程車', emoji: '🚕', sen: 'The taxi is yellow.', szh: '計程車是黃色的。', sfx: 'horn' },
      { en: 'ambulance', zh: '救護車', emoji: '🚑', sen: 'The ambulance helps people.', szh: '救護車幫助大家。', sfx: 'siren' },
      { en: 'fire truck', zh: '消防車', emoji: '🚒', sen: 'The fire truck is red.', szh: '消防車是紅色的。', sfx: 'siren' },
      { en: 'police car', zh: '警車', emoji: '🚓', sen: 'The police car goes wee-oo.', szh: '警車嗚伊嗚伊叫。', sfx: 'siren' },
      { en: 'helicopter', zh: '直升機', emoji: '🚁', sen: 'The helicopter can hover.', szh: '直升機會停在空中。', sfx: 'heli' },
      { en: 'ship', zh: '大船', emoji: '🚢', sen: 'The ship is very big.', szh: '大船好大好大。', sfx: 'boat' },
      { en: 'rocket', zh: '火箭', emoji: '🚀', sen: 'The rocket goes to the moon.', szh: '火箭飛向月亮。', sfx: 'rocket' },
      { en: 'scooter', zh: '滑板車', emoji: '🛴', sen: 'I push my scooter.', szh: '我滑滑板車。', sfx: 'whoosh' },
      { en: 'tractor', zh: '拖拉機', emoji: '🚜', sen: 'The tractor works on the farm.', szh: '拖拉機在農場工作。', sfx: 'engine' },
      { en: 'subway', zh: '捷運', emoji: '🚇', sen: 'The subway goes underground.', szh: '捷運在地下跑。', sfx: 'train' },
      { en: 'van', zh: '廂型車', emoji: '🚐', sen: 'The van has many seats.', szh: '廂型車有好多座位。', sfx: 'engine' },
      { en: 'hot air balloon', zh: '熱氣球', emoji: '🎈', sen: 'The hot air balloon floats up.', szh: '熱氣球飄上天。', sfx: 'whoosh' },
    ],
  },
  {
    id: 'animals',
    name: '動物',
    emoji: '🦁',
    color: '#ffb703',
    words: [
      { en: 'dog', zh: '小狗', emoji: '🐶', sen: 'The dog says woof woof.', szh: '小狗汪汪叫。', sfx: 'woof' },
      { en: 'cat', zh: '小貓', emoji: '🐱', sen: 'The cat says meow.', szh: '小貓喵喵叫。', sfx: 'meow' },
      { en: 'bird', zh: '小鳥', emoji: '🐦', sen: 'The bird can sing.', szh: '小鳥會唱歌。', sfx: 'tweet' },
      { en: 'fish', zh: '小魚', emoji: '🐟', sen: 'The fish can swim.', szh: '小魚會游泳。', sfx: 'bubble' },
      { en: 'elephant', zh: '大象', emoji: '🐘', sen: 'The elephant has a long nose.', szh: '大象鼻子長。', sfx: 'trumpet' },
      { en: 'lion', zh: '獅子', emoji: '🦁', sen: 'The lion says roar!', szh: '獅子吼吼叫。', sfx: 'roar' },
      { en: 'tiger', zh: '老虎', emoji: '🐯', sen: 'The tiger has stripes.', szh: '老虎有條紋。', sfx: 'roar' },
      { en: 'monkey', zh: '猴子', emoji: '🐵', sen: 'The monkey loves bananas.', szh: '猴子愛吃香蕉。', sfx: 'squeak' },
      { en: 'rabbit', zh: '兔子', emoji: '🐰', sen: 'The rabbit can hop.', szh: '兔子跳跳跳。', sfx: 'boing' },
      { en: 'bear', zh: '熊熊', emoji: '🐻', sen: 'The bear likes honey.', szh: '熊熊喜歡蜂蜜。', sfx: 'growl' },
      { en: 'cow', zh: '乳牛', emoji: '🐮', sen: 'The cow says moo.', szh: '乳牛哞哞叫。', sfx: 'moo' },
      { en: 'pig', zh: '小豬', emoji: '🐷', sen: 'The pig says oink.', szh: '小豬呼嚕嚕。', sfx: 'oink' },
      { en: 'horse', zh: '馬', emoji: '🐴', sen: 'The horse runs fast.', szh: '馬兒跑得快。', sfx: 'neigh' },
      { en: 'sheep', zh: '綿羊', emoji: '🐑', sen: 'The sheep says baa.', szh: '綿羊咩咩叫。', sfx: 'baa' },
      { en: 'duck', zh: '鴨子', emoji: '🦆', sen: 'The duck says quack.', szh: '鴨子呱呱叫。', sfx: 'quack' },
      { en: 'chicken', zh: '小雞', emoji: '🐔', sen: 'The chicken lays eggs.', szh: '母雞會生蛋。', sfx: 'cluck' },
      { en: 'frog', zh: '青蛙', emoji: '🐸', sen: 'The frog jumps high.', szh: '青蛙跳得高。', sfx: 'ribbit' },
      { en: 'snake', zh: '蛇', emoji: '🐍', sen: 'The snake says hiss.', szh: '蛇嘶嘶叫。', sfx: 'hiss' },
      { en: 'penguin', zh: '企鵝', emoji: '🐧', sen: 'The penguin walks funny.', szh: '企鵝走路搖搖擺擺。', sfx: 'quack' },
      { en: 'giraffe', zh: '長頸鹿', emoji: '🦒', sen: 'The giraffe has a long neck.', szh: '長頸鹿脖子長。', sfx: 'pop' },
    ],
  },
  {
    id: 'heroes',
    name: '超級英雄',
    emoji: '🦸',
    color: '#ff6b9d',
    words: [
      { en: 'hero', zh: '英雄', emoji: '🦸', sen: 'You are my hero.', szh: '你是我的英雄。', sfx: 'fanfare' },
      { en: 'cape', zh: '披風', emoji: '🧣', sen: 'The cape is red.', szh: '披風是紅色的。', sfx: 'whoosh' },
      { en: 'mask', zh: '面具', emoji: '🎭', sen: 'The mask hides my face.', szh: '面具遮住我的臉。', sfx: 'pop' },
      { en: 'shield', zh: '盾牌', emoji: '🛡️', sen: 'The shield keeps me safe.', szh: '盾牌保護我。', sfx: 'clang' },
      { en: 'power', zh: '力量', emoji: '⚡', sen: 'The hero has super power.', szh: '英雄有超能力。', sfx: 'zap' },
      { en: 'strong', zh: '強壯', emoji: '💪', sen: 'I am very strong.', szh: '我好強壯。', sfx: 'power' },
      { en: 'brave', zh: '勇敢', emoji: '🦸‍♀️', sen: 'Be brave!', szh: '要勇敢喔！', sfx: 'fanfare' },
      { en: 'fast', zh: '快', emoji: '💨', sen: 'The hero runs fast.', szh: '英雄跑得快。', sfx: 'whoosh' },
      { en: 'jump', zh: '跳', emoji: '🤸', sen: 'I can jump high.', szh: '我跳得好高。', sfx: 'boing' },
      { en: 'robot', zh: '機器人', emoji: '🤖', sen: 'The robot can walk.', szh: '機器人會走路。', sfx: 'robot' },
      { en: 'monster', zh: '怪獸', emoji: '👾', sen: 'The monster is funny.', szh: '怪獸好好笑。', sfx: 'growl' },
      { en: 'magic', zh: '魔法', emoji: '✨', sen: 'Magic is amazing.', szh: '魔法好神奇。', sfx: 'magic' },
      { en: 'save', zh: '拯救', emoji: '🆘', sen: 'Heroes save people.', szh: '英雄拯救大家。', sfx: 'fanfare' },
      { en: 'team', zh: '團隊', emoji: '🤝', sen: 'We are a super team.', szh: '我們是超級團隊。', sfx: 'ding' },
      { en: 'villain', zh: '壞蛋', emoji: '🦹', sen: 'The villain runs away.', szh: '壞蛋逃走了。', sfx: 'growl' },
      { en: 'laser', zh: '雷射', emoji: '💥', sen: 'The laser goes zap!', szh: '雷射咻咻叫。', sfx: 'zap' },
      { en: 'armor', zh: '盔甲', emoji: '🦾', sen: 'The armor is shiny.', szh: '盔甲亮晶晶。', sfx: 'clang' },
      { en: 'rescue', zh: '救援', emoji: '🚨', sen: 'Rescue is coming!', szh: '救援來了！', sfx: 'siren' },
      { en: 'sky', zh: '天空', emoji: '☁️', sen: 'The hero flies in the sky.', szh: '英雄在天空飛。', sfx: 'whoosh' },
      { en: 'super', zh: '超級', emoji: '🌟', sen: 'You are super!', szh: '你超級棒！', sfx: 'fanfare' },
    ],
  },
  {
    id: 'daily',
    name: '日用品',
    emoji: '🪥',
    color: '#845ec2',
    words: [
      { en: 'cup', zh: '杯子', emoji: '🥛', sen: 'I drink milk from my cup.', szh: '我用杯子喝牛奶。', sfx: 'pop' },
      { en: 'spoon', zh: '湯匙', emoji: '🥄', sen: 'I eat soup with a spoon.', szh: '我用湯匙喝湯。', sfx: 'ding' },
      { en: 'fork', zh: '叉子', emoji: '🍴', sen: 'I use a fork.', szh: '我用叉子吃飯。', sfx: 'ding' },
      { en: 'plate', zh: '盤子', emoji: '🍽️', sen: 'The food is on the plate.', szh: '食物在盤子上。', sfx: 'ding' },
      { en: 'bowl', zh: '碗', emoji: '🥣', sen: 'The bowl is full.', szh: '碗裝得滿滿的。', sfx: 'pop' },
      { en: 'toothbrush', zh: '牙刷', emoji: '🪥', sen: 'I brush my teeth.', szh: '我刷刷牙。', sfx: 'brush' },
      { en: 'soap', zh: '肥皂', emoji: '🧼', sen: 'Wash your hands with soap.', szh: '用肥皂洗洗手。', sfx: 'bubble' },
      { en: 'towel', zh: '毛巾', emoji: '🧖', sen: 'I dry my hands with a towel.', szh: '我用毛巾擦擦手。', sfx: 'pop' },
      { en: 'chair', zh: '椅子', emoji: '🪑', sen: 'I sit on the chair.', szh: '我坐在椅子上。', sfx: 'pop' },
      { en: 'door', zh: '門', emoji: '🚪', sen: 'Please close the door.', szh: '請關門。', sfx: 'knock' },
      { en: 'bed', zh: '床', emoji: '🛏️', sen: 'I sleep in my bed.', szh: '我在床上睡覺。', sfx: 'magic' },
      { en: 'lamp', zh: '燈', emoji: '💡', sen: 'Turn on the lamp.', szh: '打開燈燈。', sfx: 'tick' },
      { en: 'clock', zh: '時鐘', emoji: '⏰', sen: 'The clock says tick tock.', szh: '時鐘滴答滴答。', sfx: 'tick' },
      { en: 'umbrella', zh: '雨傘', emoji: '☂️', sen: 'I use an umbrella in the rain.', szh: '下雨天撐雨傘。', sfx: 'bubble' },
      { en: 'key', zh: '鑰匙', emoji: '🔑', sen: 'The key opens the door.', szh: '鑰匙開門門。', sfx: 'jingle' },
      { en: 'phone', zh: '電話', emoji: '📱', sen: 'The phone goes ring ring.', szh: '電話鈴鈴響。', sfx: 'ring' },
      { en: 'book', zh: '書', emoji: '📖', sen: 'I read a book.', szh: '我看書。', sfx: 'whoosh' },
      { en: 'pencil', zh: '鉛筆', emoji: '✏️', sen: 'I draw with a pencil.', szh: '我用鉛筆畫畫。', sfx: 'brush' },
      { en: 'scissors', zh: '剪刀', emoji: '✂️', sen: 'Scissors cut paper.', szh: '剪刀剪紙。', sfx: 'snip' },
      { en: 'mirror', zh: '鏡子', emoji: '🪞', sen: 'I see myself in the mirror.', szh: '我照鏡子。', sfx: 'magic' },
    ],
  },
  {
    id: 'fruits',
    name: '水果',
    emoji: '🍎',
    color: '#ff6b6b',
    words: [
      { en: 'apple', zh: '蘋果', emoji: '🍎', sen: 'The apple is red.', szh: '蘋果紅紅的。', sfx: 'pop' },
      { en: 'banana', zh: '香蕉', emoji: '🍌', sen: 'The banana is yellow.', szh: '香蕉黃黃的。', sfx: 'boing' },
      { en: 'orange', zh: '柳橙', emoji: '🍊', sen: 'The orange is juicy.', szh: '柳橙好多汁。', sfx: 'pop' },
      { en: 'grape', zh: '葡萄', emoji: '🍇', sen: 'Grapes are purple.', szh: '葡萄紫紫的。', sfx: 'pop' },
      { en: 'watermelon', zh: '西瓜', emoji: '🍉', sen: 'The watermelon is big.', szh: '西瓜好大一顆。', sfx: 'knock' },
      { en: 'strawberry', zh: '草莓', emoji: '🍓', sen: 'I love strawberries.', szh: '我愛草莓。', sfx: 'ding' },
      { en: 'pineapple', zh: '鳳梨', emoji: '🍍', sen: 'The pineapple is sweet.', szh: '鳳梨甜甜的。', sfx: 'ding' },
      { en: 'peach', zh: '桃子', emoji: '🍑', sen: 'The peach is soft.', szh: '桃子軟軟的。', sfx: 'pop' },
      { en: 'pear', zh: '梨子', emoji: '🍐', sen: 'The pear is green.', szh: '梨子綠綠的。', sfx: 'pop' },
      { en: 'lemon', zh: '檸檬', emoji: '🍋', sen: 'The lemon is sour.', szh: '檸檬酸酸的。', sfx: 'boing' },
      { en: 'mango', zh: '芒果', emoji: '🥭', sen: 'The mango is yummy.', szh: '芒果好好吃。', sfx: 'ding' },
      { en: 'cherry', zh: '櫻桃', emoji: '🍒', sen: 'Cherries are small.', szh: '櫻桃小小的。', sfx: 'pop' },
      { en: 'kiwi', zh: '奇異果', emoji: '🥝', sen: 'The kiwi is fuzzy.', szh: '奇異果毛毛的。', sfx: 'pop' },
      { en: 'coconut', zh: '椰子', emoji: '🥥', sen: 'The coconut is hard.', szh: '椰子硬硬的。', sfx: 'knock' },
      { en: 'blueberry', zh: '藍莓', emoji: '🫐', sen: 'Blueberries are blue.', szh: '藍莓藍藍的。', sfx: 'pop' },
      { en: 'melon', zh: '哈密瓜', emoji: '🍈', sen: 'The melon smells good.', szh: '哈密瓜香香的。', sfx: 'pop' },
      { en: 'tomato', zh: '番茄', emoji: '🍅', sen: 'The tomato is round.', szh: '番茄圓圓的。', sfx: 'pop' },
      { en: 'avocado', zh: '酪梨', emoji: '🥑', sen: 'The avocado is green.', szh: '酪梨綠綠的。', sfx: 'pop' },
      { en: 'green apple', zh: '青蘋果', emoji: '🍏', sen: 'The green apple is crunchy.', szh: '青蘋果脆脆的。', sfx: 'pop' },
      { en: 'juice', zh: '果汁', emoji: '🧃', sen: 'I drink apple juice.', szh: '我喝蘋果汁。', sfx: 'bubble' },
    ],
  },
];
