/* =====================================================
   單字庫 — 每個主題至少 20 個單字
   欄位：en 英文、zh 中文、emoji 圖示、
        sen 英文例句、szh 中文例句、sfx 音效代號
   想新增單字：直接照格式加一行即可
   ===================================================== */
const THEMES = [
  {
    id: 'vehicles',
    name: '交通工具',
    emoji: '🚗',
    color: '#4ecdc4',
    words: [
      { en: 'car', zh: '車車', emoji: '🚗', sen: 'The car goes beep beep.', szh: '車車叭叭叫。', sfx: 'horn' },
      { en: 'bus', zh: '公車', emoji: '🚌', sen: 'The bus is big.', szh: '公車好大呀。', sfx: 'engine' },
      { en: 'train', zh: '火車', emoji: '🚂', sen: 'The train goes choo choo.', szh: '火車嘟嘟叫。', sfx: 'train' },
      { en: 'airplane', zh: '飛機', emoji: '✈️', sen: 'The airplane flies high.', szh: '飛機飛得好高。', sfx: 'plane' },
      { en: 'boat', zh: '小船', emoji: '⛵', sen: 'The boat is on the water.', szh: '小船在水上漂。', sfx: 'boat' },
      { en: 'bicycle', zh: '腳踏車', emoji: '🚲', sen: 'I ride my bicycle.', szh: '我騎腳踏車。', sfx: 'bell' },
      { en: 'motorcycle', zh: '摩托車', emoji: '🏍️', sen: 'The motorcycle is fast.', szh: '摩托車跑得快。', sfx: 'engine' },
      { en: 'truck', zh: '卡車', emoji: '🚚', sen: 'The truck carries toys.', szh: '卡車載著玩具。', sfx: 'engine' },
      { en: 'taxi', zh: '計程車', emoji: '🚕', sen: 'The taxi is yellow.', szh: '計程車是黃色的。', sfx: 'horn' },
      { en: 'ambulance', zh: '救護車', emoji: '🚑', sen: 'The ambulance helps people.', szh: '救護車幫助大家。', sfx: 'siren' },
      { en: 'fire truck', zh: '消防車', emoji: '🚒', sen: 'The fire truck is red.', szh: '消防車是紅色的。', sfx: 'siren' },
      { en: 'police car', zh: '警車', emoji: '🚓', sen: 'The police car goes wee-oo.', szh: '警車嗚伊嗚伊叫。', sfx: 'siren' },
      { en: 'helicopter', zh: '直升機', emoji: '🚁', sen: 'The helicopter can hover.', szh: '直升機會停在空中。', sfx: 'heli' },
      { en: 'ship', zh: '大船', emoji: '🚢', sen: 'The ship is very big.', szh: '大船好大好大。', sfx: 'boat' },
      { en: 'rocket', zh: '火箭', emoji: '🚀', sen: 'The rocket goes to the moon.', szh: '火箭飛向月亮。', sfx: 'rocket' },
      { en: 'scooter', zh: '滑板車', emoji: '🛴', sen: 'I push my scooter.', szh: '我滑滑板車。', sfx: 'whoosh' },
      { en: 'tractor', zh: '拖拉機', emoji: '🚜', sen: 'The tractor works on the farm.', szh: '拖拉機在農場工作。', sfx: 'engine' },
      { en: 'subway', zh: '捷運', emoji: '🚇', sen: 'The subway goes underground.', szh: '捷運在地下跑。', sfx: 'train' },
      { en: 'van', zh: '廂型車', emoji: '🚐', sen: 'The van has many seats.', szh: '廂型車有好多座位。', sfx: 'engine' },
      { en: 'hot air balloon', zh: '熱氣球', emoji: '🎈', sen: 'The hot air balloon floats up.', szh: '熱氣球飄上天。', sfx: 'whoosh' },
      { en: 'jeep', zh: '吉普車', emoji: '🚙', sen: 'The jeep goes on the bumpy road.', szh: '吉普車開在顛簸的路上。', sfx: 'engine' },
      { en: 'tram', zh: '電車', emoji: '🚊', sen: 'The tram runs on rails.', szh: '電車在軌道上跑。', sfx: 'train' },
      { en: 'sled', zh: '雪橇', emoji: '🛷', sen: 'The sled slides on the snow.', szh: '雪橇在雪上滑。', sfx: 'whoosh' },
      { en: 'skateboard', zh: '滑板', emoji: '🛹', sen: 'I ride my skateboard.', szh: '我玩滑板。', sfx: 'whoosh' },
      { en: 'canoe', zh: '獨木舟', emoji: '🛶', sen: 'The canoe floats on the river.', szh: '獨木舟在河上漂。', sfx: 'bubble' },
      { en: 'ferry', zh: '渡輪', emoji: '⛴️', sen: 'The ferry carries many cars.', szh: '渡輪載了好多車。', sfx: 'boat' },
      { en: 'race car', zh: '賽車', emoji: '🏎️', sen: 'The race car is super fast.', szh: '賽車超級快。', sfx: 'engine' },
      { en: 'garbage truck', zh: '垃圾車', emoji: '🚛', sen: 'The garbage truck picks up trash.', szh: '垃圾車來收垃圾。', sfx: 'engine' },
      { en: 'cable car', zh: '纜車', emoji: '🚡', sen: 'The cable car goes up the mountain.', szh: '纜車上山去。', sfx: 'whoosh' },
      { en: 'ferris wheel', zh: '摩天輪', emoji: '🎡', sen: 'The ferris wheel turns slowly.', szh: '摩天輪慢慢轉。', sfx: 'jingle' },
    ],
  },
  {
    id: 'animals',
    name: '動物',
    emoji: '🦁',
    color: '#ffb703',
    words: [
      { en: 'dog', zh: '小狗', emoji: '🐶', sen: 'The dog says woof woof.', szh: '小狗汪汪叫。', sfx: 'woof' },
      { en: 'cat', zh: '小貓', emoji: '🐱', sen: 'The cat says meow.', szh: '小貓喵喵叫。', sfx: 'meow' },
      { en: 'bird', zh: '小鳥', emoji: '🐦', sen: 'The bird can sing.', szh: '小鳥會唱歌。', sfx: 'tweet' },
      { en: 'fish', zh: '小魚', emoji: '🐟', sen: 'The fish can swim.', szh: '小魚會游泳。', sfx: 'bubble' },
      { en: 'elephant', zh: '大象', emoji: '🐘', sen: 'The elephant has a long nose.', szh: '大象鼻子長。', sfx: 'trumpet' },
      { en: 'lion', zh: '獅子', emoji: '🦁', sen: 'The lion says roar!', szh: '獅子吼吼叫。', sfx: 'roar' },
      { en: 'tiger', zh: '老虎', emoji: '🐯', sen: 'The tiger has stripes.', szh: '老虎有條紋。', sfx: 'roar' },
      { en: 'monkey', zh: '猴子', emoji: '🐵', sen: 'The monkey loves bananas.', szh: '猴子愛吃香蕉。', sfx: 'squeak' },
      { en: 'rabbit', zh: '兔子', emoji: '🐰', sen: 'The rabbit can hop.', szh: '兔子跳跳跳。', sfx: 'boing' },
      { en: 'bear', zh: '熊熊', emoji: '🐻', sen: 'The bear likes honey.', szh: '熊熊喜歡蜂蜜。', sfx: 'growl' },
      { en: 'cow', zh: '乳牛', emoji: '🐮', sen: 'The cow says moo.', szh: '乳牛哞哞叫。', sfx: 'moo' },
      { en: 'pig', zh: '小豬', emoji: '🐷', sen: 'The pig says oink.', szh: '小豬呼嚕嚕。', sfx: 'oink' },
      { en: 'horse', zh: '馬', emoji: '🐴', sen: 'The horse runs fast.', szh: '馬兒跑得快。', sfx: 'neigh' },
      { en: 'sheep', zh: '綿羊', emoji: '🐑', sen: 'The sheep says baa.', szh: '綿羊咩咩叫。', sfx: 'baa' },
      { en: 'duck', zh: '鴨子', emoji: '🦆', sen: 'The duck says quack.', szh: '鴨子呱呱叫。', sfx: 'quack' },
      { en: 'chicken', zh: '小雞', emoji: '🐔', sen: 'The chicken lays eggs.', szh: '母雞會生蛋。', sfx: 'cluck' },
      { en: 'frog', zh: '青蛙', emoji: '🐸', sen: 'The frog jumps high.', szh: '青蛙跳得高。', sfx: 'ribbit' },
      { en: 'snake', zh: '蛇', emoji: '🐍', sen: 'The snake says hiss.', szh: '蛇嘶嘶叫。', sfx: 'hiss' },
      { en: 'penguin', zh: '企鵝', emoji: '🐧', sen: 'The penguin walks funny.', szh: '企鵝走路搖搖擺擺。', sfx: 'quack' },
      { en: 'giraffe', zh: '長頸鹿', emoji: '🦒', sen: 'The giraffe has a long neck.', szh: '長頸鹿脖子長。', sfx: 'pop' },
      { en: 'zebra', zh: '斑馬', emoji: '🦓', sen: 'The zebra has black and white stripes.', szh: '斑馬有黑白條紋。', sfx: 'neigh' },
      { en: 'panda', zh: '熊貓', emoji: '🐼', sen: 'The panda eats bamboo.', szh: '熊貓吃竹子。', sfx: 'growl' },
      { en: 'koala', zh: '無尾熊', emoji: '🐨', sen: 'The koala sleeps in the tree.', szh: '無尾熊在樹上睡覺。', sfx: 'squeak' },
      { en: 'owl', zh: '貓頭鷹', emoji: '🦉', sen: 'The owl says hoot at night.', szh: '貓頭鷹晚上咕咕叫。', sfx: 'tweet' },
      { en: 'whale', zh: '鯨魚', emoji: '🐳', sen: 'The whale is very very big.', szh: '鯨魚好大好大。', sfx: 'bubble' },
      { en: 'dolphin', zh: '海豚', emoji: '🐬', sen: 'The dolphin jumps out of the water.', szh: '海豚跳出水面。', sfx: 'squeak' },
      { en: 'turtle', zh: '烏龜', emoji: '🐢', sen: 'The turtle walks very slowly.', szh: '烏龜走得好慢。', sfx: 'pop' },
      { en: 'butterfly', zh: '蝴蝶', emoji: '🦋', sen: 'The butterfly has pretty wings.', szh: '蝴蝶的翅膀好漂亮。', sfx: 'magic' },
      { en: 'bee', zh: '蜜蜂', emoji: '🐝', sen: 'The bee says buzz buzz.', szh: '蜜蜂嗡嗡叫。', sfx: 'squeak' },
      { en: 'crab', zh: '螃蟹', emoji: '🦀', sen: 'The crab walks sideways.', szh: '螃蟹橫著走。', sfx: 'snip' },
    ],
  },
  {
    id: 'heroes',
    name: '超級英雄',
    emoji: '🦸',
    color: '#ff6b9d',
    words: [
      { en: 'Iron Man', zh: '鋼鐵人', emoji: '🦾', sen: 'Iron Man can fly.', szh: '鋼鐵人會飛。', sfx: 'rocket' },
      { en: 'Spider-Man', zh: '蜘蛛人', emoji: '🕷️', sen: 'Spider-Man shoots webs.', szh: '蜘蛛人會射蜘蛛絲。', sfx: 'whoosh' },
      { en: 'Captain America', zh: '美國隊長', emoji: '🛡️', sen: 'Captain America has a shield.', szh: '美國隊長有盾牌。', sfx: 'clang' },
      { en: 'Hulk', zh: '浩克', emoji: '💪', sen: 'Hulk is big and green.', szh: '浩克又大又綠。', sfx: 'roar' },
      { en: 'Thor', zh: '索爾', emoji: '🔨', sen: 'Thor has a magic hammer.', szh: '索爾有魔法鎚子。', sfx: 'zap' },
      { en: 'Black Panther', zh: '黑豹', emoji: '🐆', sen: 'Black Panther runs fast.', szh: '黑豹跑得好快。', sfx: 'growl' },
      { en: 'Captain Marvel', zh: '驚奇隊長', emoji: '⭐', sen: 'Captain Marvel flies in space.', szh: '驚奇隊長在太空飛。', sfx: 'power' },
      { en: 'Doctor Strange', zh: '奇異博士', emoji: '🪄', sen: 'Doctor Strange uses magic.', szh: '奇異博士會用魔法。', sfx: 'magic' },
      { en: 'Hawkeye', zh: '鷹眼', emoji: '🏹', sen: 'Hawkeye shoots arrows.', szh: '鷹眼射箭好準。', sfx: 'whoosh' },
      { en: 'Ant-Man', zh: '蟻人', emoji: '🐜', sen: 'Ant-Man can get very small.', szh: '蟻人會變得好小。', sfx: 'squeak' },
      { en: 'Groot', zh: '格魯特', emoji: '🌳', sen: 'Groot is a tree friend.', szh: '格魯特是樹朋友。', sfx: 'boing' },
      { en: 'Rocket', zh: '火箭浣熊', emoji: '🦝', sen: 'Rocket is a funny raccoon.', szh: '火箭是好笑的浣熊。', sfx: 'rocket' },
      { en: 'Wolverine', zh: '金鋼狼', emoji: '🐺', sen: 'Wolverine has sharp claws.', szh: '金鋼狼有利爪。', sfx: 'snip' },
      { en: 'Superman', zh: '超人', emoji: '🦸', sen: 'Superman is super strong.', szh: '超人超級強壯。', sfx: 'whoosh' },
      { en: 'Batman', zh: '蝙蝠俠', emoji: '🦇', sen: 'Batman drives the Batmobile.', szh: '蝙蝠俠開蝙蝠車。', sfx: 'engine' },
      { en: 'Wonder Woman', zh: '神力女超人', emoji: '🦸‍♀️', sen: 'Wonder Woman is brave.', szh: '神力女超人很勇敢。', sfx: 'fanfare' },
      { en: 'The Flash', zh: '閃電俠', emoji: '⚡', sen: 'The Flash runs super fast.', szh: '閃電俠跑得超級快。', sfx: 'zap' },
      { en: 'Aquaman', zh: '水行俠', emoji: '🔱', sen: 'Aquaman talks to fish.', szh: '水行俠會跟魚說話。', sfx: 'bubble' },
      { en: 'Green Lantern', zh: '綠光戰警', emoji: '💍', sen: 'Green Lantern has a magic ring.', szh: '綠光戰警有魔法戒指。', sfx: 'magic' },
      { en: 'Cyborg', zh: '鋼骨', emoji: '🤖', sen: 'Cyborg is half robot.', szh: '鋼骨是半機器人。', sfx: 'robot' },
      { en: 'Loki', zh: '洛基', emoji: '🐍', sen: 'Loki loves playing tricks.', szh: '洛基愛惡作劇。', sfx: 'magic' },
      { en: 'Vision', zh: '幻視', emoji: '💎', sen: 'Vision can fly through walls.', szh: '幻視能穿過牆壁。', sfx: 'power' },
      { en: 'Scarlet Witch', zh: '緋紅女巫', emoji: '🔮', sen: 'Scarlet Witch uses red magic.', szh: '緋紅女巫用紅色魔法。', sfx: 'magic' },
      { en: 'Falcon', zh: '獵鷹', emoji: '🦅', sen: 'Falcon flies with big wings.', szh: '獵鷹用大翅膀飛。', sfx: 'whoosh' },
      { en: 'Star-Lord', zh: '星爵', emoji: '🎧', sen: 'Star-Lord loves music.', szh: '星爵喜歡音樂。', sfx: 'jingle' },
      { en: 'Robin', zh: '羅賓', emoji: '🐦', sen: 'Robin helps Batman.', szh: '羅賓幫助蝙蝠俠。', sfx: 'boing' },
      { en: 'Supergirl', zh: '女超人', emoji: '💫', sen: 'Supergirl flies very high.', szh: '女超人飛得好高。', sfx: 'whoosh' },
      { en: 'Green Arrow', zh: '綠箭俠', emoji: '🎯', sen: 'Green Arrow never misses.', szh: '綠箭俠百發百中。', sfx: 'whoosh' },
      { en: 'Shazam', zh: '沙贊', emoji: '⚡', sen: 'Shazam calls the lightning.', szh: '沙贊呼喚閃電。', sfx: 'zap' },
      { en: 'Nightwing', zh: '夜翼', emoji: '🌙', sen: 'Nightwing jumps in the dark.', szh: '夜翼在黑夜跳躍。', sfx: 'whoosh' },
      { en: 'Food Hero', zh: 'FOOD超人', emoji: '🍱', sen: 'Food Hero eats healthy food.', szh: 'FOOD超人吃健康的食物。', sfx: 'ding' },
      { en: 'Ultraman', zh: '超人力霸王', emoji: '🔴', sen: 'Ultraman fights the monster.', szh: '超人力霸王打怪獸。', sfx: 'power' },
      { en: 'Ultraman Tiga', zh: '迪迦', emoji: '💜', sen: 'Tiga can change his colors.', szh: '迪迦會變顏色。', sfx: 'magic' },
      { en: 'Ultraman Zero', zh: '傑洛', emoji: '⚡', sen: 'Zero is super fast.', szh: '傑洛超級快。', sfx: 'zap' },
      { en: 'Ultraman Taro', zh: '太郎', emoji: '🌟', sen: 'Taro has a horn on his head.', szh: '太郎頭上有一根角。', sfx: 'fanfare' },
      { en: 'Ultraman Orb', zh: '歐布', emoji: '🔵', sen: 'Orb saves the city.', szh: '歐布拯救城市。', sfx: 'rocket' },
    ],
  },
  {
    id: 'daily',
    name: '日用品',
    emoji: '🪥',
    color: '#845ec2',
    words: [
      { en: 'cup', zh: '杯子', emoji: '🥛', sen: 'I drink milk from my cup.', szh: '我用杯子喝牛奶。', sfx: 'pop' },
      { en: 'spoon', zh: '湯匙', emoji: '🥄', sen: 'I eat soup with a spoon.', szh: '我用湯匙喝湯。', sfx: 'ding' },
      { en: 'fork', zh: '叉子', emoji: '🍴', sen: 'I use a fork.', szh: '我用叉子吃飯。', sfx: 'ding' },
      { en: 'plate', zh: '盤子', emoji: '🍽️', sen: 'The food is on the plate.', szh: '食物在盤子上。', sfx: 'ding' },
      { en: 'bowl', zh: '碗', emoji: '🥣', sen: 'The bowl is full.', szh: '碗裝得滿滿的。', sfx: 'pop' },
      { en: 'toothbrush', zh: '牙刷', emoji: '🪥', sen: 'I brush my teeth.', szh: '我刷刷牙。', sfx: 'brush' },
      { en: 'soap', zh: '肥皂', emoji: '🧼', sen: 'Wash your hands with soap.', szh: '用肥皂洗洗手。', sfx: 'bubble' },
      { en: 'towel', zh: '毛巾', emoji: '🧖', sen: 'I dry my hands with a towel.', szh: '我用毛巾擦擦手。', sfx: 'pop' },
      { en: 'chair', zh: '椅子', emoji: '🪑', sen: 'I sit on the chair.', szh: '我坐在椅子上。', sfx: 'pop' },
      { en: 'door', zh: '門', emoji: '🚪', sen: 'Please close the door.', szh: '請關門。', sfx: 'knock' },
      { en: 'bed', zh: '床', emoji: '🛏️', sen: 'I sleep in my bed.', szh: '我在床上睡覺。', sfx: 'magic' },
      { en: 'lamp', zh: '燈', emoji: '💡', sen: 'Turn on the lamp.', szh: '打開燈燈。', sfx: 'tick' },
      { en: 'clock', zh: '時鐘', emoji: '⏰', sen: 'The clock says tick tock.', szh: '時鐘滴答滴答。', sfx: 'tick' },
      { en: 'umbrella', zh: '雨傘', emoji: '☂️', sen: 'I use an umbrella in the rain.', szh: '下雨天撐雨傘。', sfx: 'bubble' },
      { en: 'key', zh: '鑰匙', emoji: '🔑', sen: 'The key opens the door.', szh: '鑰匙開門門。', sfx: 'jingle' },
      { en: 'phone', zh: '電話', emoji: '📱', sen: 'The phone goes ring ring.', szh: '電話鈴鈴響。', sfx: 'ring' },
      { en: 'book', zh: '書', emoji: '📖', sen: 'I read a book.', szh: '我看書。', sfx: 'whoosh' },
      { en: 'pencil', zh: '鉛筆', emoji: '✏️', sen: 'I draw with a pencil.', szh: '我用鉛筆畫畫。', sfx: 'brush' },
      { en: 'scissors', zh: '剪刀', emoji: '✂️', sen: 'Scissors cut paper.', szh: '剪刀剪紙。', sfx: 'snip' },
      { en: 'mirror', zh: '鏡子', emoji: '🪞', sen: 'I see myself in the mirror.', szh: '我照鏡子。', sfx: 'magic' },
      { en: 'shoes', zh: '鞋子', emoji: '👟', sen: 'I put on my shoes.', szh: '我穿上鞋子。', sfx: 'pop' },
      { en: 'hat', zh: '帽子', emoji: '🧢', sen: 'The hat keeps me cool.', szh: '帽子讓我涼涼的。', sfx: 'pop' },
      { en: 'shirt', zh: '上衣', emoji: '👕', sen: 'My shirt is blue.', szh: '我的上衣是藍色的。', sfx: 'whoosh' },
      { en: 'pants', zh: '褲子', emoji: '👖', sen: 'I wear my pants.', szh: '我穿褲子。', sfx: 'whoosh' },
      { en: 'socks', zh: '襪子', emoji: '🧦', sen: 'My socks are warm.', szh: '我的襪子暖暖的。', sfx: 'pop' },
      { en: 'backpack', zh: '背包', emoji: '🎒', sen: 'My backpack is heavy.', szh: '我的背包好重。', sfx: 'pop' },
      { en: 'glasses', zh: '眼鏡', emoji: '👓', sen: 'Glasses help me see.', szh: '眼鏡幫我看清楚。', sfx: 'ding' },
      { en: 'scarf', zh: '圍巾', emoji: '🧣', sen: 'The scarf keeps me warm.', szh: '圍巾讓我暖暖的。', sfx: 'whoosh' },
      { en: 'gloves', zh: '手套', emoji: '🧤', sen: 'I wear gloves in winter.', szh: '冬天我戴手套。', sfx: 'pop' },
      { en: 'window', zh: '窗戶', emoji: '🪟', sen: 'Please open the window.', szh: '請打開窗戶。', sfx: 'knock' },
    ],
  },
  {
    id: 'fruits',
    name: '水果蔬菜',
    emoji: '🍎',
    color: '#ff6b6b',
    words: [
      { en: 'apple', zh: '蘋果', emoji: '🍎', sen: 'The apple is red.', szh: '蘋果紅紅的。', sfx: 'pop' },
      { en: 'banana', zh: '香蕉', emoji: '🍌', sen: 'The banana is yellow.', szh: '香蕉黃黃的。', sfx: 'boing' },
      { en: 'orange', zh: '柳橙', emoji: '🍊', sen: 'The orange is juicy.', szh: '柳橙好多汁。', sfx: 'pop' },
      { en: 'grape', zh: '葡萄', emoji: '🍇', sen: 'Grapes are purple.', szh: '葡萄紫紫的。', sfx: 'pop' },
      { en: 'watermelon', zh: '西瓜', emoji: '🍉', sen: 'The watermelon is big.', szh: '西瓜好大一顆。', sfx: 'knock' },
      { en: 'strawberry', zh: '草莓', emoji: '🍓', sen: 'I love strawberries.', szh: '我愛草莓。', sfx: 'ding' },
      { en: 'pineapple', zh: '鳳梨', emoji: '🍍', sen: 'The pineapple is sweet.', szh: '鳳梨甜甜的。', sfx: 'ding' },
      { en: 'peach', zh: '桃子', emoji: '🍑', sen: 'The peach is soft.', szh: '桃子軟軟的。', sfx: 'pop' },
      { en: 'pear', zh: '梨子', emoji: '🍐', sen: 'The pear is green.', szh: '梨子綠綠的。', sfx: 'pop' },
      { en: 'lemon', zh: '檸檬', emoji: '🍋', sen: 'The lemon is sour.', szh: '檸檬酸酸的。', sfx: 'boing' },
      { en: 'mango', zh: '芒果', emoji: '🥭', sen: 'The mango is yummy.', szh: '芒果好好吃。', sfx: 'ding' },
      { en: 'cherry', zh: '櫻桃', emoji: '🍒', sen: 'Cherries are small.', szh: '櫻桃小小的。', sfx: 'pop' },
      { en: 'kiwi', zh: '奇異果', emoji: '🥝', sen: 'The kiwi is fuzzy.', szh: '奇異果毛毛的。', sfx: 'pop' },
      { en: 'coconut', zh: '椰子', emoji: '🥥', sen: 'The coconut is hard.', szh: '椰子硬硬的。', sfx: 'knock' },
      { en: 'blueberry', zh: '藍莓', emoji: '🫐', sen: 'Blueberries are blue.', szh: '藍莓藍藍的。', sfx: 'pop' },
      { en: 'melon', zh: '哈密瓜', emoji: '🍈', sen: 'The melon smells good.', szh: '哈密瓜香香的。', sfx: 'pop' },
      { en: 'tomato', zh: '番茄', emoji: '🍅', sen: 'The tomato is round.', szh: '番茄圓圓的。', sfx: 'pop' },
      { en: 'avocado', zh: '酪梨', emoji: '🥑', sen: 'The avocado is green.', szh: '酪梨綠綠的。', sfx: 'pop' },
      { en: 'green apple', zh: '青蘋果', emoji: '🍏', sen: 'The green apple is crunchy.', szh: '青蘋果脆脆的。', sfx: 'pop' },
      { en: 'juice', zh: '果汁', emoji: '🧃', sen: 'I drink apple juice.', szh: '我喝蘋果汁。', sfx: 'bubble' },
      { en: 'carrot', zh: '紅蘿蔔', emoji: '🥕', sen: 'The carrot is orange.', szh: '紅蘿蔔橘橘的。', sfx: 'pop' },
      { en: 'corn', zh: '玉米', emoji: '🌽', sen: 'The corn is yellow and sweet.', szh: '玉米黃黃甜甜的。', sfx: 'ding' },
      { en: 'potato', zh: '馬鈴薯', emoji: '🥔', sen: 'The potato grows in the ground.', szh: '馬鈴薯長在土裡。', sfx: 'knock' },
      { en: 'broccoli', zh: '花椰菜', emoji: '🥦', sen: 'Broccoli looks like a little tree.', szh: '花椰菜像小樹。', sfx: 'pop' },
      { en: 'cucumber', zh: '小黃瓜', emoji: '🥒', sen: 'The cucumber is long and green.', szh: '小黃瓜又長又綠。', sfx: 'snip' },
      { en: 'mushroom', zh: '香菇', emoji: '🍄', sen: 'The mushroom has a little hat.', szh: '香菇戴著小帽子。', sfx: 'boing' },
      { en: 'onion', zh: '洋蔥', emoji: '🧅', sen: 'The onion makes me cry.', szh: '洋蔥讓我流眼淚。', sfx: 'bubble' },
      { en: 'pumpkin', zh: '南瓜', emoji: '🎃', sen: 'The pumpkin is big and round.', szh: '南瓜又大又圓。', sfx: 'knock' },
      { en: 'pepper', zh: '甜椒', emoji: '🫑', sen: 'The pepper is crunchy.', szh: '甜椒脆脆的。', sfx: 'pop' },
      { en: 'sweet potato', zh: '地瓜', emoji: '🍠', sen: 'The sweet potato is yummy.', szh: '地瓜好好吃。', sfx: 'ding' },
    ],
  },
];
